### ISSUE TITLE
Build error on alpha release

### ISSUE THREAD

**Issue by gverdouw** [funcmike/rabbitmq-nio#30]
I've tried to update my package dependency to point at the 0.1.0 release, but I'm now getting an error from Xcode: `the target 'AMQPClient' in product 'AMQPClient' contains unsafe build flags` which seems to be due to versioned packages not allowing unsafe flags (at least if this discussion is correct: https://forums.swift.org/t/question-about-contains-unsafe-build-flags-in-spm/47677/4 )

It works if I stay pointed at `main`

That is:

```swift
.package(url: "https://github.com/funcmike/rabbitmq-nio.git", branch: "main"),
```

instead of 

```swift
.package(url: "https://github.com/funcmike/rabbitmq-nio.git", from: "0.1.0-alpha"),
```

**Comment by funcmike** [comment]
Sorry, I forgot to remove old unsafe flag. It works now try again with `.package(url: "https://github.com/funcmike/rabbitmq-nio.git", from: "0.1.0-alpha"),` (I've moved this tag v0.1.0-alpha to current commit, after this minor fix)

**Comment by gverdouw** [comment]
Yep, its all good now 👍
